Avoid JS error in login
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module angularSpinner due to:
Error: [$injector:nomod] Module 'angularSpinner' is not available! You
either misspelled the module name or forgot to load it. If registering a
module ensure that you specify the dependencies as the second argument.