Fix the below issue
reason : it happens because giving request object as a parameter of task job.

EncodeError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed